version: "3.8"
services:
  mongo_db:
    image: mongo
    restart: always
    volumes:
      - mongo_db:/data/db

  server: 
    build: ./server
    ports:
      - "4200:4200"
    volumes: 
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo_db:27017/online-cinema
      - JWT_SECRET=OJKijdf923e9ifg0$&j!@jkhf123
    depends_on:
      - mongo_db

  client: 
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/app:/app/app
    depends_on: 
      - server
volumes:
  mongo_db: {}